# Generated by Django 5.2.8 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Correo Electrónico"),
                            ("PUSH", "Notificación Push"),
                            ("SMS", "Mensaje de Texto"),
                            ("IN_APP", "Notificación en la Aplicación"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="URL Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-sent_at"],
            },
        ),
    ]
