# Generated by Django 5.2.8 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Clave de Sesión (para invitados)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
            ],
            options={
                "verbose_name": "Artículo del carrito",
                "verbose_name_plural": "Artículos del carrito",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de pago"),
                            ("PROCESSING", "En proceso"),
                            ("SHIPPED", "Enviado"),
                            ("DELIVERED", "Entregado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado del pedido",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha del pedido"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto total"
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(verbose_name="Dirección de envío"),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID de transacción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio unitario al momento de la compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo del pedido",
                "verbose_name_plural": "Artículos del pedido",
            },
        ),
    ]
