# Generated by Django 5.2.8 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código del cupón"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Porcentaje"), ("FIXED", "Monto fijo")],
                        max_length=10,
                        verbose_name="Tipo de descuento",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor del descuento",
                    ),
                ),
                (
                    "minimum_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Monto mínimo requerido",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Válido desde")),
                ("valid_to", models.DateTimeField(verbose_name="Válido hasta")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Usos máximos"
                    ),
                ),
                (
                    "uses_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usos actuales"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Cupón",
                "verbose_name_plural": "Cupones",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la promoción"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "free_shipping",
                    models.BooleanField(default=False, verbose_name="Envío gratis"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateTimeField(verbose_name="Fecha de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Promoción",
                "verbose_name_plural": "Promociones",
            },
        ),
    ]
