# Generated by Django 5.2.8 on 2025-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=255, verbose_name="Calle y número"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Estado/Provincia",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=20, verbose_name="Código postal"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Bolivia", max_length=100, verbose_name="País"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Dirección por defecto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receive_promotions",
                    models.BooleanField(
                        default=True, verbose_name="Recibir promociones y ofertas"
                    ),
                ),
                (
                    "preferred_size",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Talla preferida (e.g., M, L, XL)",
                    ),
                ),
                (
                    "style_preference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Preferencia de estilo (e.g., Casual, Formal)",
                    ),
                ),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Puntos de fidelidad"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil del Cliente",
                "verbose_name_plural": "Perfiles de Clientes",
            },
        ),
    ]
