# Generated by Django 5.2.8 on 2025-11-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Producto"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Descripción Completa")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción Corta"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Base"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destacado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="categories.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Talla (e.g., S, M, L)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Color (e.g., Rojo, Negro)",
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Ajuste de Precio (+/-)",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="SKU (Unidad de Mantenimiento de Stock)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Imagen Principal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="Producto Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de Producto",
                "verbose_name_plural": "Variantes de Producto",
                "unique_together": {("product", "size", "color")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Archivo de Imagen"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Imagen Principal"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Orden de Visualización"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productvariant",
                        verbose_name="Variante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Producto",
                "verbose_name_plural": "Imágenes de Producto",
                "ordering": ["order"],
            },
        ),
    ]
