# Generated by Django 5.2.8 on 2025-11-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Inicio del Período")),
                (
                    "predicted_quantity",
                    models.PositiveIntegerField(verbose_name="Cantidad Predicha"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Generado en"),
                ),
            ],
            options={
                "verbose_name": "Predicción de Venta",
                "verbose_name_plural": "Predicciones de Ventas",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Puntuación de Relevancia",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("COLLAB", "Filtro Colaborativo"),
                            ("CONTENT", "Basado en Contenido"),
                            ("TREND", "Tendencia General"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Recomendación",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Generado en"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Producto Recomendado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación",
                "verbose_name_plural": "Recomendaciones",
            },
        ),
    ]
